(define (squarer a b)
  (define (process-new-value)
    (if (has-value? b)
        (if (< (get-vaue b) 0)
            (error "square less then 0: SQUARER"
                   (get-value b))
            (set-value! a (sqrt b) me))
        (set-value! b (square a) me)))
  (define (process-forget-value)
    (forget-value! a me)
    (forget-value! b me)
    (process-new-value))
  (define (me request)
    (cond ((eq? request 'I-have-a-value) (process-new-value))
          ((eq? request 'I-lost-my-value) (process-forget-value))
          (else (error "Unknown request: SQUARER" request))))
  (connect a me)
  (connect b me)
  me)
